engines/libs/config/routes.rb
Libs::Engine.routes.draw do
  resources :accounts do
    member do
      get :delete
    end
  end

  resources :audios do
    member do
      get :delete
    end
  end

  resources :destinations do
    member do
      get :delete
    end
  end

  resources :grammars do
    member do
      get :delete
      get :export
    end
  end

  resources :lists do
    member do
      get :delete
    end
  end

  resources :schedules do
    member do
      get :delete
    end
  end

  resources :tables do
    member do
      get :delete
    end
  end

  root :to => 'layouts#index'
end

engines/libs/app/models/libs/account.rb
module Libs
  class Account < ActiveRecord::Base
    self.table_name = 'libs.accounts'

    # Evitamos que Rails utilice "type" como columna de herencia
    self.inheritance_column = nil

    validates_presence_of :name
    validates_uniqueness_of :name, :scope => :users_id
    validates :email, email: true, :if => :validates_email
    validates_presence_of :email, :if => :validates_email
    validates :url, url: true, :if => :validates_http
    validates_presence_of :url, :if => :validates_http
    validates_numericality_of :port, :allow_blank => true, :if => :validates_ftp
    validates_presence_of :server, :port, :folder, :user, :password, :if => :validates_ftp

    protected

      after_initialize do
        self.type ||= 'email'
      end

      before_save do
        self.product = nil if self.product.blank?
      end

    private

      # Dependiendo del tipo que se elija, se requieren unos campos u otros
      def validates_email
        self.type == 'email'
      end

      def validates_http
        self.type == 'post'
      end

      def validates_ftp
        %w(ftp sftp).include? self.type
      end
  end
end

engines/libs/app/models/libs/contact.rb
module Libs
  class Contact < ActiveRecord::Base
    self.table_name = 'libs.contacts'

    belongs_to :list, :class_name => 'Libs::List', :foreign_key => 'libs_lists_id'

    validates_numericality_of :phone_number
  end
end

engines/libs/app/controllers/libs/accounts_controller.rb
module Libs
  class AccountsController < LibsController
    before_action :add_find, :except => %w(index new create)
    before_action :add_extra_info, :except => %w(delete destroy)

    def index
      @accounts = Libs::Account.where(@global_conditions).order('id DESC').to_a
    end

    def show
    end

    def new
      @account = Libs::Account.new
      reset_cookies :accounts
    end

    def edit
      reset_cookies :accounts
    end

    def create
      @account = Libs::Account.new allowed_params
      reset_cookies :accounts

      if add_data && @account.save
        flash.now[:notice] = I18n.t('messages.success.create')
        redirect_lib
      else
        render :action => :new
      end
    end

    def update
      reset_cookies :accounts

      if @account.update_attributes allowed_params
        flash.now[:notice] = I18n.t('messages.success.update')
        redirect_lib
      else
        render :action => :edit
      end
    end

    def delete
    end

    def destroy
      if @account.destroy
        flash.now[:notice] = I18n.t('messages.success.destroy')
      else
        flash.now[:error] = I18n.t('messages.error.server')
      end

      js_redirect_to accounts_path
    end

    private

      def add_find
        @account = Libs::Account.where(id: params[:id]).first
        js_redirect_to account_path(params[:id]) if @account.users_id.blank? && params[:action] != 'show' && not WEBO_CONFIG['users']['administrators'].include? session[:user]['data']['id']
        render_error 403 if session[:user]['data']['id'] != @account.users_id || (external_engine && @account.product != external_engine)
      end

      def add_extra_info
        @products = @products.delete_if{ |x| not LIBS_CONFIG['products_libs'][x[:value]].include? 'accounts' } unless external_engine

        available_types = LIBS_CONFIG['accounts']['type'].rclone
        available_types = available_types.delete_if{ |x| LIBS_CONFIG['disabled_features']['accounts'].include? x['value'] } unless %w(development test).include? Rails.env
        @type = available_types.each{ |x| x['text'] = I18n.t(x['text']) }
      end

      def add_data
        @account.product = external_engine if external_engine
        @account.users_id = session[:user]['data']['id']
      end

      def redirect_lib
        redirect :accounts, @account.id, @account.name, accounts_path
      end

      def allowed_params
        permit_fields = [
          :name,
          :type,
          :email,
          :server,
          :port,
          :folder,
          :user,
          :password,
          :url
        ]
        permit_fields.push :product unless external_engine
        params.require(:account).permit permit_fields
      end
  end
end

engines/libs/app/controllers/libs/audios_controller.rb
module Libs
  class AudiosController < LibsController
    before_action :add_find, :except => %w(index new create)
    before_action :add_extra_info, :except => %w(delete destroy)

    def index
      @audios = Libs::Audio.where(@global_conditions).order('id DESC').to_a
    end

    def show
    end

    def new
      @audio = Libs::Audio.new
      reset_cookies :audios
    end

    def edit
      reset_cookies :audios
    end

    def create
      @audio = Libs::Audio.new allowed_params
      reset_cookies :audios

      if add_data && @audio.save
        flash.now[:notice] = I18n.t('messages.success.create')
        redirect_lib
      else
        render :action => :new
      end
    end

    def update
      reset_cookies :audios

      if @audio.update_attributes allowed_params
        flash.now[:notice] = I18n.t('messages.success.update')
        redirect_lib
      else
        render :action => :edit
      end
    end

    def delete
    end

    def destroy
      if @audio.destroy
        flash.now[:notice] = I18n.t('messages.success.destroy')
      else
        flash.now[:error] = I18n.t('messages.error.server')
      end

      js_redirect_to audios_path
    end

    private

      def add_find
        @audio = Libs::Audio.where(id: params[:id]).first
        js_redirect_to audio_path(params[:id]) if @audio.users_id.blank? && params[:action] != 'show' && not WEBO_CONFIG['users']['administrators'].include? session[:user]['data']['id']
        render_error 403 if session[:user]['data']['id'] != @audio.users_id || (external_engine && @audio.product != external_engine)
      end

      def add_extra_info
        @products = @products.delete_if{ |x| not LIBS_CONFIG['products_libs'][x[:value]].include? 'audios' } unless external_engine
      end

      def add_data
        @audio.product = external_engine if external_engine
        @audio.users_id = session[:user]['data']['id']
      end

      def redirect_lib
        redirect :audios, @audio.id, @audio.name, audios_path
      end

      def allowed_params
        permit_fields = [
          :name,
          :att
        ]
        permit_fields.push :product unless external_engine
        params.require(:audio).permit permit_fields
      end
  end
end

engines/libs/app/controllers/libs/destinations_controller.rb
module Libs
  class DestinationsController < LibsController
    before_action :add_find, :except => %w(index new create)
    before_action :add_extra_info, :except => %w(delete destroy)

    def index
      @destinations = Libs::Destination.where(@global_conditions).order('id DESC').to_a
    end

    def show
    end

    def new
      @destination = Libs::Destination.new
      reset_cookies :destinations
    end

    def edit
      reset_cookies :destinations
    end

    def create
      @destination = Libs::Destination.new allowed_params
      reset_cookies :destinations

      if add_data && @destination.save
        flash.now[:notice] = I18n.t('messages.success.create')
        redirect_lib
      else
        render :action => :new
      end
    end

    def update
      reset_cookies :destinations

      if @destination.update_attributes allowed_params
        flash.now[:notice] = I18n.t('messages.success.update')
        redirect_lib
      else
        render :action => :edit
      end
    end

    def delete
    end

    def destroy
      if @destination.destroy
        flash.now[:notice] = I18n.t('messages.success.destroy')
      else
        flash.now[:error] = I18n.t('messages.error.server')
      end

      js_redirect_to destinations_path
    end

    private

      def add_find
        @destination = Libs::Destination.where(id: params[:id]).first
        js_redirect_to destination_path(params[:id]) if @destination.users_id.blank? && params[:action] != 'show' && not WEBO_CONFIG['users']['administrators'].include? session[:user]['data']['id']
        render_error 403 if session[:user]['data']['id'] != @destination.users_id || (external_engine && @destination.product != external_engine)
      end

      def add_extra_info
        @products = @products.delete_if{ |x| not LIBS_CONFIG['products_libs'][x[:value]].include? 'destinations' } unless external_engine
      end

      def add_data
        @destination.product = external_engine if external_engine
        @destination.users_id = session[:user]['data']['id']
      end

      def redirect_lib
        redirect :destinations, @destination.id, @destination.name, destinations_path
      end

      def allowed_params
        permit_fields = [
          :name,
          :phone_number
        ]
        permit_fields.push :product unless external_engine
        params.require(:destination).permit permit_fields
      end
  end
end

engines/libs/app/controllers/libs/grammars_controller.rb
module Libs
  class GrammarsController < LibsController
    before_action :add_find, :except => %w(index new create)
    before_action :add_extra_info, :except => %w(export delete destroy)

    def index
      @grammars = Libs::Grammar.where(@global_conditions).order('id DESC').to_a
    end

    def show
    end

    def export
      render :text => @grammar.options.to_json
    end

    def new
      @grammar = Libs::Grammar.new
      reset_cookies :grammars
    end

    def edit
      reset_cookies :grammars
    end

    def create
      @grammar = Libs::Grammar.new allowed_params
      reset_cookies :grammars

      if add_data && @grammar.save
        flash.now[:notice] = I18n.t('messages.success.create')
        redirect_lib
      else
        render :action => :new
      end
    end

    def update
      reset_cookies :grammars

      if @grammar.update_attributes allowed_params
        flash.now[:notice] = I18n.t('messages.success.update')
        redirect_lib
      else
        render :action => :edit
      end
    end

    def delete
    end

    def destroy
      if @grammar.destroy
        flash.now[:notice] = I18n.t('messages.success.destroy')
      else
        flash.now[:error] = I18n.t('messages.error.server')
      end

      js_redirect_to grammars_path
    end

    private

      def add_find
        @grammar = Libs::Grammar.where(id: params[:id]).includes(:options).first
        js_redirect_to grammar_path(params[:id]) if @grammar.users_id.blank? && params[:action] != 'show' && not WEBO_CONFIG['users']['administrators'].include? session[:user]['data']['id']
        render_error 403 if session[:user]['data']['id'] != @grammar.users_id || (external_engine && @grammar.product != external_engine)
      end

      def add_extra_info
        @products = @products.delete_if{ |x| not LIBS_CONFIG['products_libs'][x[:value]].include? 'grammars' } unless external_engine
      end

      def add_data
        @grammar.product = external_engine if external_engine
        @grammar.users_id = session[:user]['data']['id']
      end

      def redirect_lib
        redirect :grammars, @grammar.id, @grammar.name, grammars_path
      end

      def allowed_params
        permit_fields = [
          :name
        ]
        permit_fields.push :product unless external_engine
        params.require(:grammar).permit(permit_fields).tap do |whitelisted|
          whitelisted[:related_options] = params[:grammar][:related_options]
        end
      end
  end
end

engines/libs/app/controllers/libs/layouts_controller.rb
module Libs
  class LayoutsController < LibsController
    def index
      render :file => 'layouts/products', :layout => false
    end
  end
end

engines/libs/app/controllers/libs/libs_controller.rb
module Libs
  class LibsController < ::ApplicationController
    include Libs::LibsHelper
    helper Libs::Engine.helpers

    layout 'pages'

    before_action :libs_auth, :default_values, unless: :is_public_page?

    def reset_cookies(name)
      if params.include? :window
        # Borramos las cookies por si el usuario cierra la ventana sin finalizar el proceso
        cookies["#{name}_last_id".to_sym] = nil
        cookies["#{name}_last_name".to_sym] = nil
      end
    end

    private

      def libs_auth
        # Si el usuario está intentando ver una librería para la que no tiene ningún producto asociado, se lo impedimos
        lib_name = params[:controller].gsub('libs/', String.new)
        lib_name = lib_name.split('/')[0] if lib_name.include? '/'
        render_error 403 unless params[:controller] == 'libs/layouts' || get_allowed_libs.include? lib_name
      end

      def default_values
        # Layout
        if params[:controller] == 'libs/layouts'
          # Menu: dejamos sólo las librerías para las que tenga permisos, y ponemos el listado de la primera como página principal
          allowed_libs = get_allowed_libs
          @engine_menu = engine_config['menu'].rclone.delete_if{ |x| x.include? 'key' && not allowed_libs.include? x['key'] }
          @engine_menu[0]['link'] = "libs.#{allowed_libs[0]}_path"
        end
        # Hacemos que, si estamos accediendo a las librerías desde otro engine, sólo se vean sus elementos
        @global_conditions = [ 'users_id = ? OR users_id IS NULL', session[:user]['data']['id'] ]
        if external_engine
          @global_conditions[0] = "(#{@global_conditions[0]}) AND product = ?"
          @global_conditions.push external_engine
        else
          # Productos
          @products = Array.new
          (LIBS_CONFIG['products_libs'].rclone.map{ |k,v| k.to_s } & session[:user]['products']).each do |x|
            @products.push({ :value => x, :text => I18n.t("products.#{x}") })
          end
        end
      end
  end
end

engines/libs/app/controllers/libs/lists_controller.rb
module Libs
  class ListsController < LibsController
    before_action :add_find, :except => %w(index new create)
    before_action :add_extra_info, :except => %w(delete destroy)

    def index
      @lists = Libs::List.includes(:contacts).where(@global_conditions).order("#{Libs::List.table_name}.id DESC").to_a
    end

    def show
    end

    def new
      @list = Libs::List.new
      reset_cookies :lists
    end

    def edit
      reset_cookies :lists
    end

    def create
      @list = Libs::List.new allowed_params
      reset_cookies :lists
      summary = @list.save if add_data

      if summary.is_a?(Array)
        flash.now[:notice] = summary_notice(summary)
        redirect_lib
      else
        render :action => :new
      end
    end

    def update
      reset_cookies :lists
      summary = @list.update_attributes allowed_params

      if summary.is_a?(Array)
        # Si se ha cambiado el tipo o los contactos de la lista, notificamos al sistema
        unless @list.previous_changes.blank?
          update_system_url_params = "/#{@list.id}"
          update_system_url_params += "/type/#{@list.type}" if @list.previous_changes.include? 'type'
          update_system_url_params += "/contacts" if @list.previous_changes.include? 'att_updated_at'
          get_url_response "#{LIBS_CONFIG['lists']['system_urls']['update'][Rails.env]}#{update_system_url_params}"
        end

        flash.now[:notice] = summary_notice(summary)
        redirect_lib
      else
        render :action => :edit
      end
    end

    def delete
    end

    def destroy
      if @list.destroy
        # Notificamos al sistema de la eliminación de la lista
        get_url_response "#{LIBS_CONFIG['lists']['system_urls']['delete'][Rails.env]}/#{@list.id}"

        flash.now[:notice] = I18n.t('messages.success.destroy')
      else
        flash.now[:error] = I18n.t('messages.error.server')
      end

      js_redirect_to lists_path
    end

    private

      def add_find
        @list = Libs::List.where(id: params[:id]).includes(:contacts).first
        js_redirect_to list_path(params[:id]) if @list.users_id.blank? && params[:action] != 'show' && not WEBO_CONFIG['users']['administrators'].include? session[:user]['data']['id']
        render_error 403 if session[:user]['data']['id'] != @list.users_id || (external_engine && @list.product != external_engine)
      end

      def add_extra_info
        @products = @products.delete_if{ |x| not LIBS_CONFIG['products_libs'][x[:value]].include? 'lists' } unless external_engine
        @type = LIBS_CONFIG['lists']['type'].rclone.each{ |x| x['text'] = I18n.t(x['text']) }
      end

      def add_data
        @list.product = external_engine if external_engine
        @list.users_id = session[:user]['data']['id']
      end

      def redirect_lib
        redirect :lists, @list.id, @list.name, lists_path
      end

      def summary_notice(data)
        "#{I18n.t('messages.success.' + params[:action])}</p><p>#{I18n.t('libs.lists.contacts.message', added: data[0], discarded: data[1], total: (data[0] + data[1]))}."
      end

      def allowed_params
        permit_fields = [
          :name,
          :type,
          :att,
          :replace_contacts
        ]
        permit_fields.push :product unless external_engine
        params.require(:list).permit permit_fields
      end
  end
end

engines/libs/app/views/libs/grammars/_form.html.erb
<fieldset>
  <div class="section">
    <span class="label"><%= auto_label_for f, :name %></span>

    <%= smart_text_field f, :name %>
  </div>

  <% unless external_engine %>
    <div class="section">
      <span class="label"><%= auto_label_for f, :product %></span>

      <%= smart_select_field f, :product, options_from_hash_for_select(@products, :value, :text, @grammar.product, true) %>
    </div>
  <% end %>

  <div class="section">
    <span class="label"><%= I18n.t('fields.controllers.libs__grammars.options') %></span>

    <div class="alert alert-info fade in">
      <p><%= icon :info, I18n.t('libs.grammars.values_info'), class: 'fa-fw' %></p>
    </div>

    <table class="bordered-table">
      <thead>
        <tr>
          <th width="45%"><%= I18n.t('fields.shared.name') %></th>
          <th width="45%" class="block"><%= I18n.t('fields.controllers.libs__grammars.values') %></th>
          <th width="10%" class="block">&nbsp;</th>
        </tr>
      </thead>
      <tbody id="options_list">
        <%= render 'libs/grammars/option', f: f, num: 0, name: @grammar.related_options['o_0']['name'], related_values: @grammar.related_options['o_0']['related_values'] %>
        <% unless @grammar.related_options.blank? %>
          <% @grammar.related_options.each do |k,v| %>
            <%
              num = k.split('_')[1].to_i
              unless num == 0
            %>
              <%= render 'libs/grammars/option', f: f, num: num, name: v['name'], related_values: v['related_values'] %>
            <% end %>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</fieldset>

<% content_for :js_tags do %>
  <%= render 'assets_calls/javascripts/tagsinput' %>
<% end %>

<% if params.include? :ajax_loaded %>

  <%= hidden_field_tag :ajax_loaded %>
  <%= hidden_field_tag :content_div, '#lib' %>

  <div class="ribbon-content">
    <%= link_to I18n.t('actions.close'), 'javascript:close_div("lib");', :class => 'btn btn-default btn-xs' %>
  </div>

<% else %>

  <div class="ribbon-content">
    <%= hlink_to I18n.t('misc.list'), grammars_path, :class => 'btn btn-default btn-xs' %>
  </div>

<% end %>

engines/libs/app/views/libs/grammars/_option.html.erb
<tr id="grammar_o_<%= num %>">
  <td><%= smart_text_field f, [ "[related_options][o_#{num}][name]", name ] %></td>

  <td class="block"><%= text_field_tag "grammar[related_options][o_#{num}][related_values]", related_values, class: 'tagsinput' %></td>

  <td class="block">
    <% if num == 0 %>
      <%= link_to icon('plus-square', nil, class: 'fa-1-5x'), "javascript:new_grammar_option('#{escape_javascript(render 'libs/grammars/option', f: f, num: 'x', name: String.new, related_values: Array.new)}');" %>
    <% else %>
      <%= link_to icon('minus-square', nil, class: 'fa-1-5x'), "javascript:remove_object($('#grammar_o_x'));" %>
    <% end %>
  </td>
</tr>

engines/libs/app/views/libs/grammars/delete.html.erb
<%= form String.new, :url => grammar_path(@grammar), :html => { :id => "delete_grammar_#{@grammar.id}_form", :method => :delete } do |f| %>
  <div class="alert alert-warning fade in">
    <%= icon :warning, String.new, class: 'fa-fw' %> <%= raw I18n.t('libs.grammars.delete.text', name: @grammar.name) %>
  </div>

  <%= submit_tag I18n.t('actions.delete'), :class => 'btn btn-primary' %>
  <%= hlink_to I18n.t('actions.return'), grammars_path, :class => 'btn btn-default' %>
<% end %>

<div class="ribbon-content">
  <%= hlink_to I18n.t('actions.edit'), edit_grammar_path(@grammar), :class => 'btn btn-default btn-xs' %>
</div>

engines/libs/app/views/libs/grammars/edit.html.erb
<h1 class="page-title">
  <%= icon 'comments-o', @grammar.name, class: 'fa-fw' %>
</h1>

<section id="widget-grid">
  <div id="edit_grammar_<%= @grammar.id %>" class="jarviswidget jarviswidget-color-darken" data-widget-editbutton="false" data-widget-togglebutton="false" data-widget-deletebutton="false">
    <header>
      <span class="widget-icon"><%= icon :edit %></span>
      <h2><%= I18n.t('misc.data') %></h2>
    </header>

    <div>
      <div class="widget-body no-padding">
        <%= form(@grammar, :url => grammar_path, :html => { :class => 'smart-form' }) do |f| %>
          <%= render 'form', f: f %>

          <footer>
            <%= f.submit I18n.t('actions.edit'), :class => 'btn btn-primary' %>
            <% if params.include? :ajax_loaded %>
              <%= link_to I18n.t('actions.close'), "javascript:close_div('lib');", :class => 'btn btn-default' %>
            <% else %>
              <%= hlink_to I18n.t('actions.return'), grammars_path, :class => 'btn btn-default' %>
            <% end %>
          </footer>
        <% end %>
      </div>
    </div>
  </div>
</section>

engines/libs/app/views/libs/grammars/index.html.erb
<h1 class="page-title">
  <%= icon 'comments-o', I18n.t('libs.grammars.index.title'), class: 'fa-fw' %>
</h1>

<% unless @grammars.blank? %>

  <section id="widget-grid">
    <div id="grammars" class="jarviswidget jarviswidget-color-darken" data-widget-editbutton="false" data-widget-togglebutton="false" data-widget-deletebutton="false">
      <header>
        <span class="widget-icon"><%= icon :table %></span>
        <h2><%= I18n.t('misc.data') %></h2>
      </header>

      <div>
        <div class="widget-body no-padding">
          <table class="data-table table table-striped table-bordered table-hover">
            <thead>
              <tr>
                <th><%= I18n.t('fields.shared.id') %></th>
                <th><%= icon 'comments-o', String.new, class: 'text-muted hidden-md hidden-sm hidden-xs' %> <%= I18n.t('fields.shared.name') %></th>
                <% unless external_engine %>
                  <th><%= I18n.t('fields.shared.product') %></th>
                <% end %>
                <th class="options"><%= I18n.t('misc.options') %></th>
              </tr>
            </thead>
            <tbody>
              <% @grammars.each do |grammar| %>
                <tr>
                  <td><%= grammar.id %></td>
                  <td><%= grammar.name %></td>
                  <% unless external_engine %>
                    <td><%= I18n.t("products.#{grammar.product}") unless grammar.product.blank? %></td>
                  <% end %>
                  <td class="options">
                    <% if grammar.users_id.blank? && not WEBO_CONFIG['users']['administrators'].include? session[:user]['data']['id'] %>
                      <%= hlink_to grammar_path(grammar) do %>
                        <%= icon :eye %>
                        <%= I18n.t('actions.view') %>
                      <% end %>
                    <% else %>
                      <%= hlink_to edit_grammar_path(grammar) do %>
                        <%= icon :edit %>
                        <%= I18n.t('actions.edit') %>
                      <% end %>

                      <%= hlink_to delete_grammar_path(grammar) do %>
                        <%= icon :remove %>
                        <%= I18n.t('actions.delete') %>
                      <% end %>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </section>

  <% content_for :js_tags do %>
    <%= render 'assets_calls/javascripts/data_tables' %>
  <% end %>

<% else %>

  <div class="alert alert-info fade in">
    <p><%= icon :info, I18n.t('messages.error.no_results'), class: 'fa-fw' %></p>
  </div>

<% end %>

engines/libs/app/views/libs/grammars/new.html.erb
<h1 class="page-title">
  <%= icon 'comments-o', I18n.t('libs.grammars.create.title'), class: 'fa-fw' %>
</h1>

<section id="widget-grid">
  <div id="create_grammar" class="jarviswidget jarviswidget-color-darken" data-widget-editbutton="false" data-widget-togglebutton="false" data-widget-deletebutton="false">
    <header>
      <span class="widget-icon"><%= icon :edit %></span>
      <h2><%= I18n.t('misc.data') %></h2>
    </header>

    <div>
      <div class="widget-body no-padding">
        <%= form(@grammar, :html => { :class => 'smart-form' }) do |f| %>
          <%= render 'form', f: f %>

          <footer>
            <%= f.submit I18n.t('actions.create'), :class => 'btn btn-primary' %>
            <% if params.include? :ajax_loaded %>
              <%= link_to I18n.t('actions.close'), "javascript:close_div('lib');", :class => 'btn btn-default' %>
            <% else %>
              <%= hlink_to I18n.t('actions.return'), grammars_path, :class => 'btn btn-default' %>
            <% end %>
          </footer>
        <% end %>
      </div>
    </div>
  </div>
</section>

engines/libs/app/views/libs/grammars/show.html.erb
<h1 class="page-title">
  <%= icon 'comments-o', @grammar.name, class: 'fa-fw' %>
</h1>

<section id="widget-grid">
  <div id="grammar_<%= @grammar.id %>" class="jarviswidget jarviswidget-color-darken" data-widget-editbutton="false" data-widget-togglebutton="false" data-widget-deletebutton="false">
    <header>
      <span class="widget-icon"><%= icon :edit %></span>
      <h2><%= I18n.t('misc.data') %> (<%= I18n.t('misc.read_only') %>)</h2>
    </header>

    <div>
      <div class="widget-body no-padding">
        <table class="table table-bordered">
          <tr>
            <td><strong><%= I18n.t('fields.shared.name') %></strong></td>
            <td><%= @grammar.name %></td>
          </tr>
          <% unless @grammar.product.blank? %>
            <tr>
              <td><strong><%= I18n.t('fields.shared.product') %></strong></td>
              <td><%= I18n.t("products.#{@grammar.product}") %></td>
            </tr>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</section>

<% if params.include? :ajax_loaded %>

  <div class="ribbon-content">
    <%= link_to I18n.t('actions.close'), 'javascript:close_div("lib");', :class => 'btn btn-default btn-xs' %>
  </div>

<% else %>

  <div class="ribbon-content">
    <%= hlink_to I18n.t('misc.list'), grammars_path, :class => 'btn btn-default btn-xs' %>
  </div>

<% end %>